### ISSUE TITLE
Ansible-Lint and Test CI

### ISSUE THREAD

**Issue by p-rintz** [wiggels/ansible-role-snipe-it#2]
Hi, 

you dont have the github discussions enabled on this repo, so Im opening this as an issue.

What are your thoughts on using Ansible Lint on the role?
Currently, many changes that would need to be made to be fully "compliant". 

Just an excerpt:

```
fqcn-builtins: Use FQCN for builtin actions.
tasks/clean_server_installs.yml:2 Task/Handler: Remove all apache, php, and nginx software

yaml: truthy value should be one of [false, true] (yaml[truthy])
tasks/clean_server_installs.yml:9

yaml: truthy value should be one of [false, true] (yaml[truthy])
tasks/clean_server_installs.yml:10

yaml: no new line character at the end of file (yaml[new-line-at-end-of-file])
tasks/clean_server_installs.yml:11

yaml: truthy value should be one of [false, true] (yaml[truthy])
tasks/clean_server_installs.yml:11

yaml: truthy value should be one of [false, true] (yaml[truthy])
tasks/install_packages.yml:5

yaml: truthy value should be one of [false, true] (yaml[truthy])
tasks/install_packages.yml:22

yaml: truthy value should be one of [false, true] (yaml[truthy])
tasks/install_packages.yml:43

yaml: truthy value should be one of [false, true] (yaml[truthy])
tasks/install_packages.yml:49

yaml: no new line character at the end of file (yaml[new-line-at-end-of-file])
tasks/install_packages.yml:50

yaml: truthy value should be one of [false, true] (yaml[truthy])
tasks/install_packages.yml:50
```

**Comment by wiggels** [comment]
I am going to look into this and a CI to test install and run a verification. Some are valid, the truthy ones are...sorta a false positive. While in YAML they are wrong, ansible accepts and in many places in documentation uses yes/no instead of true/false.

**Comment by p-rintz** [comment]
Yes, the whole truthy issue is annoying me somewhat. As the Ansible Docs and Ansible-Lint dont agree on what to do there. I brought this up in the Ansible Community Workgroup and its currently being discussed what the best solution to the issue is.

In the end, there is no real need to change it if you are happy with yes/no. You could always exclude the truthy test or add yes/no as acceptable values, as well.

If you are interested in the issue:
https://github.com/ansible-community/community-topics/issues/116

**Comment by wiggels** [comment]
Github action for ansible-lint now in place
https://github.com/wiggels/ansible-role-snipe-it/commit/96bb7690d5ebd618eac978aa65e20bae00bfb7f9
