### ISSUE TITLE
Composer install failing with: "Unsupported parameters for (ansible.legacy.command) module"

### ISSUE THREAD

**Issue by cTurtle98** [wiggels/ansible-role-snipe-it#5]
git this error
```
fatal: [k0cdf-srv1-snipeit]: FAILED! => {"changed": false, "cmd": "/usr/bin/apt-key export 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C", "msg": "E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation", "rc": 255, "stderr": "E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation\n", "stderr_lines": ["E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation"], "stdout": "", "stdout_lines": []}
```
with this ansible

https://github.com/cTurtle98/K0CDF-AREDN/commit/ba00b65c75493540ede7f711510762b9921c43a3

**Comment by wiggels** [comment]
I will look into this. What OS version are you attempting the install on?

**Comment by cTurtle98** [comment]
> I will look into this. What OS version are you attempting the install on?

I am installing on the ubuntu 22.04 LXC container template that comes with proxmox 7.3-4

**Comment by cTurtle98** [comment]
I also found that I had to manually run this command to make the ansible work

```bash
ansible-galaxy collection install nginxinc.nginx_core
```

it wasn't installed with 
```bash
ansible-galaxy install wiggels.snipeit
```

**Comment by cTurtle98** [comment]
https://github.com/snipe/snipe-it/releases/tag/v6.0.14
6.0.14 has been released by the way

**Comment by cTurtle98** [comment]
```
TASK [wiggels.snipeit : Checkout v6.0.13 of Snipe-IT] ************************************************************************************************************
changed: [k0cdf-srv1-snipeit]

TASK [wiggels.snipeit : Write .env file to snipe-it directory] ***************************************************************************************************
changed: [k0cdf-srv1-snipeit]

TASK [wiggels.snipeit : Install composer] ************************************************************************************************************************
fatal: [k0cdf-srv1-snipeit]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.legacy.command) module: warn. Supported parameters include: argv, _raw_params, stdin_add_newline, creates, stdin, strip_empty_ends, chdir, executable, _uses_shell, removes."}
```

had another error while running. got further than last time after manually installing the nginx collection

**Comment by wiggels** [comment]
On the nginx collection dependency:
 I say go ahead and create an issue to remove the dependency on the collection completely. There are not a lot of collection features we are using in it honestly--can be easily replicated in the role itself.

For the version bump:
You can create a separate issue for it. There does not appear to be any breaking changes so you can go ahead and submit a PR as well if you would like. Should just entail changing [this line](https://github.com/wiggels/ansible-role-snipe-it/blob/main/defaults/main.yml#L6). That's an easy way to get listed as a contributor :grin:.

I will rename this issue with the Composer installation issue and look further into it.

**Comment by wiggels** [comment]
Can you give me the output of `ansible --version` from where you are running ansible?

**Comment by cTurtle98** [comment]
> Can you give me the output of `ansible --version` from where you are running ansible?

```
ciaran@ciaran-ThinkPad-P14s-Gen-2a:~/projects/K0CDF-AREDN$ ansible --version
ansible [core 2.14.1]
  config file = None
  configured module search path = ['/home/ciaran/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ciaran/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/ciaran/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ciaran/.local/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
ciaran@ciaran-ThinkPad-P14s-Gen-2a:~/projects/K0CDF-AREDN$ 
```

**Comment by wiggels** [comment]
Looks like they depreciated the warn arg in 2.14 https://github.com/ansible/ansible/pull/70504
I have a fix coming in just a few minutes.
